# Google Cloud Run Configuration for PropFlow
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: propflow-platform
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Auto-scaling configuration
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
        
        # Resource allocation
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
        run.googleapis.com/cpu-throttling: "false"
        
        # Database connections
        run.googleapis.com/cloudsql-instances: PROJECT_ID:REGION:propflow-db
        
        # VPC connector for private services
        run.googleapis.com/vpc-access-connector: propflow-connector
        run.googleapis.com/vpc-access-egress: private-ranges-only
        
        # Security
        run.googleapis.com/execution-environment: gen2
        
    spec:
      # Request timeout
      timeoutSeconds: 300
      
      # Container concurrency
      containerConcurrency: 80
      
      # Service account for accessing Google Cloud services
      serviceAccountName: propflow-service-account@PROJECT_ID.iam.gserviceaccount.com
      
      containers:
      - image: gcr.io/PROJECT_ID/propflow-platform:latest
        name: propflow-container
        
        ports:
        - name: http1
          containerPort: 8080
          
        env:
        # Environment variables from secrets
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
              
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-url
              key: latest
              
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: latest
              
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: stripe-secret-key
              key: latest
              
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
              
        # Direct environment variables
        - name: NODE_ENV
          value: "production"
          
        - name: PORT
          value: "8080"
          
        - name: GOOGLE_CLOUD_PROJECT
          value: "PROJECT_ID"
          
        - name: GOOGLE_CLOUD_REGION
          value: "REGION"
          
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
            
        # Health check probes
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          timeoutSeconds: 5
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: propflow-frontend
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "50"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1"
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/propflow-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "https://propflow-platform-PROJECT_ID.a.run.app"
        - name: NODE_ENV
          value: "production"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: propflow-ai
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "2"
    spec:
      containers:
      - image: gcr.io/PROJECT_ID/propflow-ai:latest
        ports:
        - containerPort: 8000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest
