# Google Cloud Build configuration for PropFlow platform
steps:
  # Build and push API Gateway
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-api-gateway:$SHORT_SHA'
      - './backend/api-gateway'
    id: 'build-api-gateway'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-api-gateway:$SHORT_SHA'
    id: 'push-api-gateway'

  # Build and push Auth Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-auth-service:$SHORT_SHA'
      - './backend/auth-service'
    id: 'build-auth-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-auth-service:$SHORT_SHA'
    id: 'push-auth-service'

  # Build and push Property Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-property-service:$SHORT_SHA'
      - './backend/property-service'
    id: 'build-property-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-property-service:$SHORT_SHA'
    id: 'push-property-service'

  # Build and push Tenant Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-tenant-service:$SHORT_SHA'
      - './backend/tenant-service'
    id: 'build-tenant-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-tenant-service:$SHORT_SHA'
    id: 'push-tenant-service'

  # Build and push Payment Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-payment-service:$SHORT_SHA'
      - './backend/payment-service'
    id: 'build-payment-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-payment-service:$SHORT_SHA'
    id: 'push-payment-service'

  # Build and push Notification Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-notification-service:$SHORT_SHA'
      - './backend/notification-service'
    id: 'build-notification-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-notification-service:$SHORT_SHA'
    id: 'push-notification-service'

  # Build and push Maintenance Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-maintenance-service:$SHORT_SHA'
      - './backend/maintenance-service'
    id: 'build-maintenance-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-maintenance-service:$SHORT_SHA'
    id: 'push-maintenance-service'

  # Build and push Booking Service
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-booking-service:$SHORT_SHA'
      - './backend/booking-service'
    id: 'build-booking-service'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-booking-service:$SHORT_SHA'
    id: 'push-booking-service'

  # Build and push AI Services
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-ai-services:$SHORT_SHA'
      - './ai-services'
    id: 'build-ai-services'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-ai-services:$SHORT_SHA'
    id: 'push-ai-services'

  # Build and push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/propflow-frontend:$SHORT_SHA'
      - './frontend'
    id: 'build-frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/propflow-frontend:$SHORT_SHA'
    id: 'push-frontend'

  # Deploy to Cloud Run
  # API Gateway
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'propflow-api-gateway'
      - '--image'
      - 'gcr.io/$PROJECT_ID/propflow-api-gateway:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '4000'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=4000'
    id: 'deploy-api-gateway'

  # Auth Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'propflow-auth-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/propflow-auth-service:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--port'
      - '4001'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'NODE_ENV=production,AUTH_SERVICE_PORT=4001'
    id: 'deploy-auth-service'

  # Property Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'propflow-property-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/propflow-property-service:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--port'
      - '4002'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - 'NODE_ENV=production,PROPERTY_SERVICE_PORT=4002'
    id: 'deploy-property-service'

  # AI Services
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'propflow-ai-services'
      - '--image'
      - 'gcr.io/$PROJECT_ID/propflow-ai-services:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--port'
      - '8000'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--max-instances'
      - '3'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,AI_SERVICE_PORT=8000'
    id: 'deploy-ai-services'

  # Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'propflow-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/propflow-frontend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
    id: 'deploy-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '3600s'